[project]
name = "htram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=2.1.1",
    "esptool>=5.3.1",
    "pyserial>=3.5",
]

[dependency-groups]
dev = [
    "aiousbwatcher>=1.1.2",
    "homeassistant>=2025.4.4",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
